/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vision;

import javax.swing.JOptionPane;

/**
 *
 * @author ed
 */
public class ScreenLogin extends javax.swing.JFrame {

    /**
     * Creates new form ScreenLogin
     */
    public ScreenLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Attention = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jPasswordFieldCode = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jButtonLogoff = new javax.swing.JButton();
        jLabelImagelogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(null);

        Attention.setBackground(new java.awt.Color(0, 153, 204));
        Attention.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Attention.setForeground(new java.awt.Color(255, 255, 255));
        Attention.setText("RESTRICTED ACESS");
        Attention.setToolTipText("");
        getContentPane().add(Attention);
        Attention.setBounds(210, 20, 180, 26);

        lblUser.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("User");
        getContentPane().add(lblUser);
        lblUser.setBounds(310, 80, 50, 20);

        lblPassword.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPassword.setText("Password");
        getContentPane().add(lblPassword);
        lblPassword.setBounds(287, 110, 90, 26);
        getContentPane().add(jTextFieldUser);
        jTextFieldUser.setBounds(390, 80, 160, 21);

        jPasswordFieldCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldCodeActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordFieldCode);
        jPasswordFieldCode.setBounds(390, 110, 160, 21);

        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogin);
        jButtonLogin.setBounds(330, 170, 68, 27);

        jButtonLogoff.setText("Log Off");
        jButtonLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoffActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogoff);
        jButtonLogoff.setBounds(420, 170, 86, 27);

        jLabelImagelogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Chave 2.png"))); // NOI18N
        jLabelImagelogin.setText("jLabel2");
        getContentPane().add(jLabelImagelogin);
        jLabelImagelogin.setBounds(10, 20, 240, 260);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tecnologiafundo3.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 580, 310);

        setSize(new java.awt.Dimension(577, 307));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldCodeActionPerformed
   
     if (jTextFieldUser.getText().equals("admin")&&jPasswordFieldCode.getText().equals("123")){
         Main good = new Main();
            good.setVisible(true);
        JOptionPane.showMessageDialog(rootPane, "Confirmed Acess");
        
    }
        
    }//GEN-LAST:event_jPasswordFieldCodeActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        if (jTextFieldUser.getText().equals("admin")&&jPasswordFieldCode.getText().equals("123")){
        Main good = new Main();
            good.setVisible(true);
        JOptionPane.showMessageDialog(rootPane, "Confirmed Acess");    
    
      dispose(); //logoffice/finish screen / fecha a janela
      
    }
        else{
            JOptionPane.showMessageDialog(rootPane,"Acess Failure");
            
        }          
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoffActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonLogoffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Attention;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonLogoff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelImagelogin;
    private javax.swing.JPasswordField jPasswordFieldCode;
    private javax.swing.JTextField jTextFieldUser;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
